CREATE SCHEMA MOVIE;
USE MOVIE;

CREATE TABLE ACTOR(
 ACT_ID INTEGER PRIMARY KEY,
 ACT_NAME VARCHAR(20),
 ACT_GENDER CHAR(1)
);
DESC ACTOR;

CREATE TABLE DIRECTOR(
 DIR_ID INTEGER PRIMARY KEY,
 DIR_NAME VARCHAR(20),
 DIR_PHONE INTEGER
);
DESC DIRECTOR;

CREATE TABLE MOVIES(
 MOV_ID INTEGER PRIMARY KEY,
 MOV_TITLE VARCHAR(25),
 MOV_YEAR INTEGER,
 MOV_LANG VARCHAR(20),
 DIR_ID INTEGER,
 FOREIGN KEY (DIR_ID) REFERENCES DIRECTOR(DIR_ID)
);
DESC MOVIES;




